name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        key:  

    - name: Ionic Preparation
      run: |
        npm install -g @ionic/cli
        npx npm-force-resolutions

    - name: Ionic Build 🔧
      run: |
        export PUBLIC_URL=https://swipe-the-curve.github.io/swipe-the-curve/${GITHUB_REF##*/}/
        npm install
        ionic build

    - name: Test
      run: npm test -- --watchAll=false

    
    - uses: actions/upload-artifact@v1
      with:
        name: swipe-the-curve-web
        path: build/

  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: swipe-the-curve-web
  
    - name: Get Tag Name
      id: get_tag
      run: echo ::set-output name=GIT_TAG::$(echo ${GITHUB_REF##*/})

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: swipe-the-curve-web/
        TARGET_FOLDER: ${{ steps.get_tag.outputs.GIT_TAG }}
        DEBUG: true
        GIT_CONFIG_NAME: Dr. Corona
        GIT_CONFIG_EMAIL: dr.corona@the-imperfection.de
