name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        key:  

    - name: Ionic Preparation
      run: |
        npm install -g @ionic/cli
        npx npm-force-resolutions

    - name: Ionic Build 🔧
      env:
        PUBLIC_URL: https://swipe-the-curve.github.io/swipe-the-curve/${GITHUB_REF##*/}/
      run: |
        npm install
        ionic build
    
    - uses: actions/upload-artifact@v1
      with:
        name: swipe-the-curve-web
        path: build/

  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: swipe-the-curve-web
    
    - name: Print folder structure (DEBUG)
      run: |
        ls -ahl swipe-the-curve-web

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: swipe-the-curve-web/
        TARGET_FOLDER: ${GITHUB_REF##*/}
        DEBUG: true
        GIT_CONFIG_NAME: Dr. Corona
        GIT_CONFIG_EMAIL: dr.corona@the-imperfection.de
