name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        key:  

    - name: Ionic Preparation
      run: |
        npm install -g @ionic/cli
        npx npm-force-resolutions

    - name: Ionic Build
      run: |
        npm install
        ionic build
    
    - uses: actions/upload-artifact@v1
      with:
        name: swipe-the-curve-web
        path: build/

  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: swipe-the-curve-web

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: swipe-the-curve-web/build # The folder the action should deploy.
          TARGET_FOLDER: master
          DEBUG: true
